### PR TITLE
SECURITY-1877 Remove warning from opsgenie-plugin

### PR DESCRIPTION
**Pull request by akyuznurettin**
The vulnerability has been fixed in this [PR](https://github.com/jenkinsci/opsgenie-plugin/pull/8).
You can check the latest plugin from [here](https://updates.jenkins.io/download/plugins/opsgenie/). e.g. `1.10`

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
The change that you've proposed will remove the security warning from the 1.9 version of the plugin and from all previous versions of the plugin.  That's not what you want.

The pull request needs to be changed to have a regular expression in the pattern that will match all releases prior to the release that includes the fix.  See the `pattern` lines for other plugins in the repository for examples of pattern matches that work well.

**Comment by akyuznurettin** [comment]
> The change that you've proposed will remove the security warning from the 1.9 version of the plugin and from all previous versions of the plugin. That's not what you want.
> 
> The pull request needs to be changed to have a regular expression in the pattern that will match all releases prior to the release that includes the fix. See the `pattern` lines for other plugins in the repository for examples of pattern matches that work well.

Oops, I am on it, thank you for your quick response

**Comment by akyuznurettin** [comment]
> The change that you've proposed will remove the security warning from the 1.9 version of the plugin and from all previous versions of the plugin. That's not what you want.
> 
> The pull request needs to be changed to have a regular expression in the pattern that will match all releases prior to the release that includes the fix. See the `pattern` lines for other plugins in the repository for examples of pattern matches that work well.



> > The change that you've proposed will remove the security warning from the 1.9 version of the plugin and from all previous versions of the plugin. That's not what you want.
> > The pull request needs to be changed to have a regular expression in the pattern that will match all releases prior to the release that includes the fix. See the `pattern` lines for other plugins in the repository for examples of pattern matches that work well.
> 
> Oops, I am on it, thank you for your quick response

@MarkEWaite Hopefully, the regex is correct.

**Comment by yaroslavafenkin** [comment]
Hi @akyuznurettin,

I've tested the fix locally, `apiKey`s are now stored encrypted, but values are not masked in the UI:

* https://github.com/jenkinsci/opsgenie-plugin/blob/feb63f0f27aba164128a02b7662408c20a2b44a0/src/main/resources/com/opsgenie/integration/jenkins/OpsGenieNotifier/config.jelly#L15
* https://github.com/jenkinsci/opsgenie-plugin/blob/feb63f0f27aba164128a02b7662408c20a2b44a0/src/main/resources/com/opsgenie/integration/jenkins/OpsGenieNotifier/global.jelly#L17

See https://www.jenkins.io/doc/developer/security/secrets/#secrets-and-configuration-forms

**Comment by akyuznurettin** [comment]
> re not masked in the UI:



> Hi @akyuznurettin,
> 
> I've tested the fix locally, `apiKey`s are now stored encrypted, but values are not masked in the UI:
> 
> * https://github.com/jenkinsci/opsgenie-plugin/blob/feb63f0f27aba164128a02b7662408c20a2b44a0/src/main/resources/com/opsgenie/integration/jenkins/OpsGenieNotifier/config.jelly#L15
> * https://github.com/jenkinsci/opsgenie-plugin/blob/feb63f0f27aba164128a02b7662408c20a2b44a0/src/main/resources/com/opsgenie/integration/jenkins/OpsGenieNotifier/global.jelly#L17
> 
> See https://www.jenkins.io/doc/developer/security/secrets/#secrets-and-configuration-forms

Thank you @yaroslavafenkin , we are keeping that API key is visible in our UI(Opsgenie), because user needs to log in to see those API keys in UI. Do you think that is it mandatory change for this vulnerability?

**Comment by akyuznurettin** [comment]
> Hi @akyuznurettin,
> 
> I've tested the fix locally, `apiKey`s are now stored encrypted, but values are not masked in the UI:
> 
> * https://github.com/jenkinsci/opsgenie-plugin/blob/feb63f0f27aba164128a02b7662408c20a2b44a0/src/main/resources/com/opsgenie/integration/jenkins/OpsGenieNotifier/config.jelly#L15
> * https://github.com/jenkinsci/opsgenie-plugin/blob/feb63f0f27aba164128a02b7662408c20a2b44a0/src/main/resources/com/opsgenie/integration/jenkins/OpsGenieNotifier/global.jelly#L17
> 
> See https://www.jenkins.io/doc/developer/security/secrets/#secrets-and-configuration-forms

Thank you @yaroslavafenkin. I am on it.

**Comment by akyuznurettin** [comment]
@yaroslavafenkin I just fixed the issue in this [PR](https://github.com/jenkinsci/opsgenie-plugin/pull/9) and deploy it as 1.11. You can test it by downloading the latest version from [here](https://updates.jenkins.io/download/plugins/opsgenie/)

**Review by yaroslavafenkin — APPROVED** [review]
Re-tested, 1.11 seems fine.

**Comment by MarkEWaite** [comment]
> @MarkEWaite Could you please approve the PR? cc: @daniel-beck

I've made more mistakes with regular expressions in this repository than I've made correct implementations.  I'm not the best person to evaluate the regular expression.  I'd prefer to leave regular expression approval to @yaroslavafenkin or others on the security team.

**Review by daniel-beck — APPROVED** [review]

**Pull request merged**
