### PR TITLE
JARVIS-823 - Remove Advisor from the blacklist

### PR DESCRIPTION
**Pull request by Evildethow**

### CODE REVIEW

**Comment by daniel-beck** [comment]
This needs more context. https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin is still in the state it was abandoned in, https://wiki.jenkins.io/display/JENKINS/CloudBees+Jenkins+Advisor+Plugin still says it's discontinued, and "JARVIS" is not a public Jira instance, so not a useful reference in a public repo like this.

**Comment by Evildethow** [comment]
@daniel-beck 

> This needs more context.

Yes. It's WIP.

>  https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin is still in the state it was abandoned in

My intention was to copy the files from https://github.com/cloudbees/cloudbees-jenkins-advisor-plugin
and just force push over https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin 

We won't be merging anything as we don't want the git history from the cloudbees fork.

> https://wiki.jenkins.io/display/JENKINS/CloudBees+Jenkins+Advisor+Plugin still says it's discontinued,

I can update this. I think we are ok.

>  "JARVIS" is not a public Jira instance, so not a useful reference in a public repo like this.

Please help by guiding me on what needs to be done on the community side. If I need to raise a public Jira then which project etc..

Thanks!

**Comment by daniel-beck** [comment]
> Please help by guiding me on what needs to be done on the community side. If I need to raise a public Jira then which project etc..

Well, any explanation will do as a public reference explaining why the plugin is back, even as a comment here. You're still listed as a maintainer, so this request is OK in principle.

> My intention was to copy the files from https://github.com/cloudbees/cloudbees-jenkins-advisor-plugin
> and just force push over https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin
> 
> We won't be merging anything as we don't want the git history from the cloudbees fork.

The specific action of force-pushing erases existing history. Perhaps it's good enough to just have a single commit that brings the plugin from 2017 to 2019 without retaining any history from in between?

**Comment by Evildethow** [comment]
> Well, any explanation will do as a public reference explaining why the plugin is back, even as a comment here. You're still listed as a maintainer, so this request is OK in principle.

Lead generation for CloudBees. Configuring Advisor requires providing an email.

> The specific action of force-pushing erases existing history. Perhaps it's good enough to just have a single commit that brings the plugin from 2017 to 2019 without retaining any history from in between?

Yes. That makes sense.

Thanks, @daniel-beck

**Comment by Evildethow** [comment]
Depends on https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin/pull/29

**Comment by daniel-beck** [comment]
@Evildethow Thanks. Please let me know when this can be merged. If I merge it now, it will publish the 2017 release for download.

**Comment by Evildethow** [comment]
Thanks, @daniel-beck 

https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin/pull/29 is merged.

Do I need to do a `mvn release ...` of the plugin first?

**Pull request merged**
