### PR TITLE
Remove ambiguously versioned releases

### PR DESCRIPTION
**Pull request by daniel-beck**
lib-versionnumber considers versions `whatever` and `whatever.0` to be equivalent. This means update-center2 cannot properly determine which of the two to consider 'newer' and advertise (assuming no other differences).

A similar problem can occur with a groupId change, `org.acme:my-plugin:1.0` and `com:acme:my-plugin:1.0` can both exist and one will take precedence over the other.

Right now, we choose one over the other essentially randomly. It appeared that the dependency updates in 3.3.1 compared to 3.3 changed something, which caused me to file https://github.com/jenkins-infra/update-center2/pull/411.

This change would result in _neither_ version to be published. Basically, creating both `X` and `X.0` would suspend distribution of both.

Thoughts?

----

The current implementation appears to have the weakness that having `X`, `X.0`, and `X.0.0` is expected to randomly admit one of them. I'll fix it if we get consensus that doing this at all isn't a terrible idea, I'll work on this some more.

### CODE REVIEW

**Comment by daniel-beck** [comment]
I fixed the issue described in the original PR comment and added a test for it.

There are currently no warnings being logged, but if I remove a few entries of plugin releases currently suspended due to duplication, the following is logged (sorted and deduplicated):

````
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact appscanstandard-integration:ibm-security-appscanstandard-scanner:1.0.0 considered identical to appscanstandard-integration:ibm-security-appscanstandard-scanner:1.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact com.cloudera.diskrecycler:diskcheck:0.20 considered identical to org.jenkins-ci.plugins:diskcheck:0.20 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact com.etas.jenkins.plugins:text-file-operations:1.2 considered identical to com.etas.jenkins.plugins:text-file-operations:1.2.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact io.jenkins.plugins:git-forensics:0.1-alpha-1 considered identical to io.jenkins.plugins:git-forensics:0.1.0-alpha-1 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact io.jenkins.plugins:sideex:1.0 considered identical to io.jenkins.plugins:sideex:1.0.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:aliyun-container-service-deploy:0.1.0 considered identical to com.aliyun.www:aliyun-container-service-deploy:0.1.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:aliyun-container-service-deploy:0.1.1 considered identical to com.aliyun.www:aliyun-container-service-deploy:0.1.1 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:async-http-client:1.7.2 considered identical to org.jenkinsci.plugins:async-http-client:1.7.2 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:contrast-continuous-application-security:1.0 considered identical to com.contrastsecurity:contrast-continuous-application-security:1.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:elastest:1.0.0-beta1 considered identical to org.jenkins-ci.plugins:elastest:1.0-beta1 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:templating-engine:1.0 considered identical to org.jenkins-ci.plugins:templating-engine:1.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jenkins-ci.plugins:threadfix:1.4.3 considered identical to me.automationdomination:threadfix:1.4.3 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.jvnet.hudson.plugins:build-pipeline-plugin:1.0.0 considered identical to au.com.centrumsystems:build-pipeline-plugin:1.0 due to non-determinism. Neither will be published.
INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact org.owasp.dependency-check:dependency-check-jenkins-plugin:1.0.1 considered identical to org.jenkins-ci.plugins:dependency-check-jenkins-plugin:1.0.1 due to non-determinism. Neither will be published.

**Review by MarkEWaite — APPROVED** [review]

**Comment by daniel-beck** [comment]
Thanks to #456 there's a live test case right now:

    INFO    io.jenkins.update_center.Plugin#addArtifact: Found a duplicate artifact com.qualys.plugins:qualys-api-security:2.1.0 considered identical to com.qualys.plugins:qualys-api-security:2.1 due to non-determinism. Neither will be published.

**Comment by daniel-beck** [comment]
Alternative proposal in #468.

**Comment by daniel-beck** [comment]
#468 seems a lot nicer and now has two approvals, closing this for now.

**Pull request closed without merging**
