### PR TITLE
Update warnings.json

### PR DESCRIPTION
**Pull request by myroid**
upload-pgyer 1.32 fixed SECURITY-1044

### CODE REVIEW

**Comment by myroid** [comment]
upload-pgyer 1.32 fixed SECURITY-1044

**Comment by myroid** [comment]
upload-pgyer 1.32 fixed SECURITY-1044

**Comment by myroid** [comment]
Thank you very much. 
According to your suggestion, I have modified and submitted the code. 
Please check it. If there are no problems, I will release version 1.33.

**Comment by myroid** [comment]
I made a stupid mistake.
Now I have submitted the latest code.
And reorganized git commit records.
Please check it. If there are no problems, I will release version 1.33.
https://github.com/jenkinsci/upload-pgyer-plugin/commit/36fc5fd81c212366cd6c66a96b200b6cd3336e54

**Comment by daniel-beck** [comment]
@myroid Thanks for updating the PR.

Looking over the code, 1.33 seems to fix the problem. But what happened to 1.32? It's missing in https://github.com/jenkinsci/upload-pgyer-plugin/commits/master

**Comment by myroid** [comment]
Because I made a stupid mistake, version 1.32 was officially released without fixing the problem. Also request the administrator to remove version 1.32.

**Comment by daniel-beck** [comment]
@myroid Never remove bad releases from the Git history. There is no way to erase them completely, and it does a disservice to anyone who has installed them already.

**Comment by myroid** [comment]
@daniel-beck Yes, you're right. I have released the latest version 1.33. Hope users update as soon as possible.

**Comment by myroid** [comment]
What should I do next?

**Pull request merged**
