### PR TITLE
Re-releasing the Delphix Plugin

### PR DESCRIPTION
**Pull request by nick-mathison**
We plan to push/release an updated version of our Delphix plugin v3.0.0 tomorrow. 
This will replace the existing (but currently hidden) Delphix Plugin. 

This PR is meant to revert the change I made back in March. https://github.com/jenkins-infra/update-center2/pull/695

Ideally, we merge this PR around the same time [the PR here is merged. ](https://github.com/jenkinsci/delphix-plugin)

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please note this will make earlier versions of the plugin also available for download, in particular they'll be served to anyone running Jenkins older than 2.361.4 (the minimum for the updated plugin). If the intention is to not distribute them again, those old versions need to be listed individually.

Also, what's the experience upgrading from an earlier release like? The description of PR 20 reads like it's basically a different plugin with the same ID, if so, likely resulting in upgrades losing all of the data? We generally discourage that, as it goes against [our values](https://www.jenkins.io/project/governance/#compatibility-matters). The PR even removes the prior `compatibleSinceVersion` declaration entirely instead of changing it to `3.0`, so users are not even warned before updating.

**Comment by nick-mathison** [comment]
Separately, we are having trouble merging our Jenkins branch which I suspect is a result of not having permissions. 
https://github.com/jenkins-infra/repository-permissions-updater/issues/3426
Your confirmation would be helpful. Thanks!

**Comment by daniel-beck** [comment]
> Please let us know how you'd like us to move forward. We believe this is the final item that is blocking our release.

Well, and the lack of a release, no? https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/delphix/ has nothing. You uploaded a snapshot, but that's it.

Note that this does not block releases, it just prevents them from being available on update sites for download by users.

**Comment by ankit-patil-hubs** [comment]
@daniel-beck As suggested by you we have released a new version 3.0.1 , same is available on [https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/delphix/](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/delphix/) for unblocking the PR merge.

**Pull request merged**
