### PR TITLE
Issue [SECURITY-1763] was fixed in version 1.1.0

### PR DESCRIPTION
**Pull request by vtintillier**
It was fixed in https://github.com/jenkinsci/flaky-test-handler-plugin/pull/14

### CODE REVIEW

**Comment by daniel-beck** [comment]
@vtintillier Thanks!

**Comment by vtintillier** [comment]
Thanks @daniel-beck 

Is it normal I still see the warning in plugin manager after getting last updates? Is there a schedule upon which a change in this repository is reflected in update center and plugins site?

image

**Comment by daniel-beck** [comment]
@vtintillier Thanks for letting me know. This shouldn't happen. Based on https://updates.jenkins.io/current/ the update center hasn't been updating in ~12 hrs. I'll let the infra folks know.

**Comment by daniel-beck** [comment]
Metadata is updated, so this should disappear from places once caches are updated.

**Comment by vtintillier** [comment]
I confirm, thanks!

image

**Pull request merged**
