### PR TITLE
deprecate performance-signature-dynatrace

### PR DESCRIPTION
**Pull request by rpionke**
The product Dynatrace AppMon is deprecated since 31.03.2021: (https://www.dynatrace.com/support/doc/appmon/)
I also added the successor of Dynatrace AppMon: https://plugins.jenkins.io/performance-signature-dynatracesaas/

FFR:
image

### CODE REVIEW

**Comment by daniel-beck** [comment]
Deprecations are better off in the dedicated resource file, there you can specify a URL explaining the deprecation: https://github.com/jenkins-infra/update-center2/blob/master/resources/deprecations.properties

**Comment by rpionke** [comment]
@daniel-beck thanks for the advise, i added the plugins in the deprecations.properties file

**Comment by basil** [comment]
Can this pull request be merged? I wasted a non-zero amount of time recently investigating potential Java 11 impact on `performance-signature-dynatrace` only to discover this PR and to realize that my effort was wasted because this plugin is deprecated. If this PR were to have been merged, I would have seen the deprecation warning and would not have wasted my time on it.

**Comment by zbynek** [comment]
@basil since git.io was discontinued, this cannot be merged and the two links it adds need replacing anyway, new PR is https://github.com/jenkins-infra/update-center2/pull/593
@rpionke for labels for the new plugin you can just add them as topics to your plugin's github repo, then you can change them later without creating PRs in this repo

**Pull request closed without merging**
