### PR TITLE
[JENKINS-55159] Add hpaat plugin 5.6 to the blacklist

### PR DESCRIPTION
**Pull request by grount**
The name of the plugin "hp-application-automation-tools-plugin" should be written as in the following link?
[repo.jenkins-ci.org](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/hp-application-automation-tools-plugin/)

Also indented the comments after #.
Let me know if any changes are required.

### CODE REVIEW

**Comment by daniel-beck** [comment]
@grount Sorry I missed the notification for this. Should we still merge this?

**Comment by grount** [comment]
@daniel-beck Yeah it still should be blacklisted, I've released 5.6.2 instead.

**Comment by daniel-beck** [comment]
@grount Thanks! Since both share the same core dependency, 5.6.2 will always supersede 5.6, so this isn't needed.

**Comment by grount** [comment]
@daniel-beck my fear is that It is still installable if not banned is it?

**Comment by daniel-beck** [comment]
Good point. It is currently still listed in the archives.

**Pull request merged**
