### PR TITLE
[JENKINS-63877] Suspend distribution of tics plugin

### PR DESCRIPTION
**Pull request by daniel-beck**
[JENKINS-63877](https://issues.jenkins-ci.org/browse/JENKINS-63877)

Temporary measure to restore plugin manager operation.

@jglick

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Fine for a hotfix. To make sure this does not happen again, please add some sort of assertion to the UC generation code.

**Review by timja — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Comment by timja** [comment]
Weird: https://github.com/jenkinsci/tics-plugin/blob/master/build.gradle#L42 can't see anything wrong there other than gradle isn't used very often =/

**Comment by daniel-beck** [comment]
@timja Based on comments in HOSTING-1021, this might not be the real build script.

**Comment by jglick** [comment]
Yeah… https://github.com/jenkinsci/tics-plugin/blob/bee100fb9a58eb5632c2ced2c499e3b5e48c5fb3/build.gradle#L11 has an _older_ version that what is in the UC, `2020.3.0.4`.

**Comment by jglick** [comment]
```
Plugin-Dependencies: tics:2020.3.0.4,tics:2020.3.0.4,structs:1.20,clou
 dbees-folder:6.9,credentials:2.3.0
```

**Comment by daniel-beck** [comment]
Commented on the lack of sources (including source archives) on HOSTING-1021. I recommend we move any further feedback for the plugin there as well.

**Pull request merged**
