### PR TITLE
Docs: Add developer guidelines

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just minor documentation update towards my experiments with Java 11.

@batmat @alecharp

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @daniel-beck

**Comment by batmat** [comment]
@oleg-nenashev plan to merge this also?

**Comment by oleg-nenashev** [comment]
@batmat I need to address concerns from @daniel-beck about the Makefile feasibility.
As an alternative, I can detach docs to a separate PR. But then there will be no Quickstart

**Comment by timja** [comment]
> @batmat I need to address concerns from @daniel-beck about the Makefile feasibility.
> As an alternative, I can detach docs to a separate PR. But then there will be no Quickstart

What's the concerns from @daniel-beck ?
This would be a good addition (I'm using this branch to set this up locally)

**Comment by daniel-beck** [comment]
I see no reason to add `make` as a dependency here. It provides no benefits over just straightforward shell scripts.

**Comment by oleg-nenashev** [comment]
@daniel-beck Do you mean the `Jenkinsfile` dependency only? Or do you want to avoid the presence of Make for development purposes as well?

**Comment by daniel-beck** [comment]
@oleg-nenashev More the latter than the former, but ideally both. I do not see what benefits it offers compared to the cost of more dependency.

**Comment by daniel-beck** [comment]
I consider this obsolete after improvements to the documentation here: https://github.com/jenkins-infra/update-center2#invocation

**Pull request closed without merging**
