### PR TITLE
--id parameter from CLI is ignored

### PR DESCRIPTION
**Pull request by nfalco79**
Actually the --id option that Main.java get from CLI is ignored.
There is also a TODO in UpdateCenterRoot bean file to use the id given in command line.

This PR fix the id in the update center produced. I know that is not intended to be used as private repository the PR does not do any different than fix something existing.

The same for connectionCheckUrl that is useful when www.google.com is not allowed in some countries or company proxy.

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Should be HTTPs for connectionCheckUrl  by default

**Comment by nfalco79** [comment]
I agree, I just moved existing URL string. Let me fix in 5 minutes to https

**Comment by nfalco79** [comment]
done

**Comment by nfalco79** [comment]
I forgot a file.

**Comment by daniel-beck** [comment]
@nfalco79 Sorry about the delay here! Does the last commit look OK to you?

**Comment by nfalco79** [comment]
Do you mean if after rebase master this fix will works as expected? I do not know, I forked after a two months to generate a custom update center based on maven central as artifact repository.
I should test it again.

**Comment by daniel-beck** [comment]
> Do you mean if after rebase master this fix will works as expected?

I don't know what you're trying to do; but this tool has used the Artifactory API for a long time. But I would expect `--id` and `--connection-check-url` to have the intended effect, yes.

**Comment by nfalco79** [comment]
Initially I started to generate a custom update site using our artifactory (company repository). After that I changed company, so this PR remain just to fix the id parameter.

**Comment by daniel-beck** [comment]
Well, crap, now I remember why I held off merging this. If only it were so easy…

**Pull request merged**
