### PR TITLE
Add sonargraph-plugin to the deprecation list

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Follow-up to https://github.com/jenkins-infra/update-center2/pull/405 . CC @daniel-beck @andreashoyerh2m

### CODE REVIEW

**Comment by daniel-beck** [comment]
Needs a URL.

**Comment by oleg-nenashev** [comment]
URL to what?

**Comment by daniel-beck** [comment]
@oleg-nenashev An URL that ideally describes what's going on with the plugin (e.g. why deprecated, what users should use instead, etc.). Please see https://github.com/jenkins-infra/update-center2#deprecations

**Comment by daniel-beck** [comment]
Note that all other comments in this file explain what the minified links point to. If you want to link to the wiki page (after disabling the redirect to the plugin site), the current comment makes sense, otherwise it does not. See https://github.com/jenkins-infra/update-center2/blob/e7265c093ebf681db938f73ca3c405df57d8084d/resources/deprecations.properties#L5

**Comment by daniel-beck** [comment]
@oleg-nenashev Ping?

**Comment by oleg-nenashev** [comment]
Pong. Feel free to amend and finalize it. You know my current situation. I
had a shitty week, and I have very difficult months ahead. I will announce
it later, but I will have to take a break in the most of community roles.

**Comment by daniel-beck** [comment]
Closing in favor of #426. I have no idea what happens with an entry without a URL, and I don't intend to find out.

**Pull request closed without merging**
