### PR TITLE
Update label-definitions.properties to deprecate plugin

### PR DESCRIPTION
**Pull request by sn-priya-jagyasi**
Update label-definitions.properties to deprecate the plugin "lightstep-incident-response-plugin"

### CODE REVIEW

**Comment by NotMyFault** [comment]
Screenshot 2022-12-13 at 10 12 16
The `deprecated` topic does already put this warning in place.

**Comment by sn-priya-jagyasi** [comment]
> Screenshot 2022-12-13 at 10 12 16 The `deprecated` topic does already put this warning in place.

This doc mentions creating pull request here [https://www.jenkins.io/doc/developer/plugin-governance/deprecating-or-removing-plugin/](https://www.jenkins.io/doc/developer/plugin-governance/deprecating-or-removing-plugin/)

**Comment by NotMyFault** [comment]
Step 2 seems redundant, given the deprecated topic does the trick.

**Comment by daniel-beck** [comment]
> This doc mentions creating pull request here https://www.jenkins.io/doc/developer/plugin-governance/deprecating-or-removing-plugin/

It says

> It can be done in 2 ways:

which means they're alternatives. One of them is enough.

**Pull request closed without merging**
