### PR TITLE
Added "orchestration" category

### PR DESCRIPTION
**Pull request by isaac-s**
For Cloudify, as well as (potentially) others

### CODE REVIEW

**Comment by daniel-beck** [comment]
It might make sense to add a corresponding PR that adds English localization to Jenkins. See https://github.com/jenkinsci/jenkins/blob/3f15ad20985066661158ee1bb0b3255e000b3081/core/src/main/resources/hudson/model/Messages.properties#L296-L333 for existing entries.

**Comment by isaac-s** [comment]
@daniel-beck done: https://github.com/jenkinsci/jenkins/pull/4822

**Comment by daniel-beck** [comment]
Right, didn't we have a discussion recently about how many plugins needed to be labeled to qualify?

@MarkEWaite may know.

So ideally @isaac-s you'd be able to identify further plugins for the category.

**Comment by isaac-s** [comment]
@daniel-beck @oleg-nenashev well, I'd consider the Terraform plugin to belong in this category as well. However, that'd be up to the Terraform plugin maintainers to decide whether they'd like to be labelled as such.

**Comment by MarkEWaite** [comment]
We discussed possibly adding some guiding threshold for the addition of categories, Unfortunately, I can't find it in my searching.  

We discussed the definitions of the categories and hypothetical assignment of plugins to categories in the [javadoc pull request](https://github.com/jenkinsci/jenkins/pull/4578#issuecomment-599857551).  However, that discussion did not delve into recommendations for number of items in a category before adding the category.  I thought that was in a discussion in on of the mailing lists, but can't find it.

This seems like a very good step forward.  Oleg's comment that there are many plugins that would fit this category is sufficient for me.  Thanks for proposing it!

**Comment by daniel-beck** [comment]
@MarkEWaite https://groups.google.com/forum/#!msg/jenkinsci-dev/mT4aVq4cJD0/aeCtebXgHAAJ

**Comment by MarkEWaite** [comment]
Yes, that proposal did not get enough traction to move any further than a proposal.

There is a comment in [`documentation.adoc`](https://raw.githubusercontent.com/jenkins-infra/jenkins.io/master/content/doc/developer/publishing/documentation.adoc) that reminds me:

```
// Need a section on categorizing plugins - how are plugin categories assigned?
```

I think the process being used in this pull request (discussion, etc.) is sufficient for this stage of the implementation of categories.

**Comment by zbynek** [comment]
Terraform plugin maintainers notified via [ticket](https://issues.jenkins.io/browse/JENKINS-64191).

**Pull request merged**
