### PR TITLE
suppress cmakebuilder-3.6.3

### PR DESCRIPTION
**Pull request by 15knots**
should have been version 2.6.3

### CODE REVIEW

**Comment by daniel-beck** [comment]
It's been 4 days. How many users do you think have already upgraded, and will never see another plugin update again (until you reach 3.7 properly)?

Unless the version number is tied to something outside the plugin, it's probably time to go with 4.0 soon(ish) IMO.

**Comment by 15knots** [comment]
Am Di., 3. Dez. 2019 um 10:31 Uhr schrieb Daniel Beck <
notifications@github.com>:

> It's been 4 days. How many users do you think have already upgraded, and
> will never see another plugin update again (until you reach 3.7 properly)?
>
Yes 4 days.  Sorry, I failed to do a proper pull request 4 days ago. Github
changed the UI to create pull request since I created my last one and I did
not recognize that.
For the numbers of users I can check the usage stats.

**Comment by 15knots** [comment]
Five users have already upgraded.

Am Di., 3. Dez. 2019 um 10:31 Uhr schrieb Daniel Beck <
notifications@github.com>:

**Comment by daniel-beck** [comment]
> Five users have already upgraded.

http://stats.jenkins.io/plugin-installation-trend/cmakebuilder.stats.json is updated monthly, and Jenkins instances report back once a day -- so that's the number of users who've updated in the first day or so of 4.

Nothing compared to Git Plugin 4.0.0-rc's 10k users, of course 😬

Just a suggestion, ultimately up to you.

**Pull request merged**
