### PR TITLE
Remove Qualys API security plugin

### PR DESCRIPTION
**Pull request by nikita-bedmutha**

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Is there any public announcement confirming it? There is https://github.com/jenkinsci/qualys-api-security-plugin/commit/26e5066115cbae310ca73752bb535ef7ef0a9410, and the plugin is now archived by @nikita-bedmutha

**Comment by nikita-bedmutha** [comment]
> Is there any public announcement confirming it? There is [jenkinsci/qualys-api-security-plugin@26e5066](https://github.com/jenkinsci/qualys-api-security-plugin/commit/26e5066115cbae310ca73752bb535ef7ef0a9410), and the plugin is now archived by @nikita-bedmutha

@oleg-nenashev , this is with regard to the internal request coming from API Security management of Qualys, and I being this integration developer need to deprecate and remove the plugin.

**Comment by nikita-bedmutha** [comment]
@oleg-nenashev , can you please merge this PR? I don't see an option, probably dont have rights.

**Comment by oleg-nenashev** [comment]
@daniel-beck @timja just to make sure, are you fine with the provided justification?

**Comment by timja** [comment]
> @daniel-beck @timja just to make sure, are you fine with the provided justification?

Shutting down a service is a standard reason for this, the repo has been archived by the maintainer, seems fine to me.

**Comment by daniel-beck** [comment]
New suspensions should specify deprecation URLs explaining the removal. Anyone currently having this installed will not be told.

**Comment by timja** [comment]
@nikita-bedmutha are you able to add one?

**Comment by nikita-bedmutha** [comment]
@timja We dont have any URL at the moment but the team is working on making public announcement to the beta customers.

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/qualys-api-security-plugin/commit/26e5066115cbae310ca73752bb535ef7ef0a9410 is a URL showing deprecation 🤷 As a placeholder, it's good enough.

**Pull request merged**
