### PR TITLE
Add support for getting default branch name, and issues urls

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by halkeye** [comment]
superseeds #355

**Comment by daniel-beck** [comment]
Overall looks reasonable. I added some minor changes.

One thing I was wondering about: Why are we claiming a default branch of `master` when we don't even publish the SCM? All the early returns in `HPI#getDefaultBranch` should return `null`, as well as some in `GitHubSource#getDefaultBranch(GitHubRepo)`. I have it prepared locally but not yet pushed in case I'm missing something. Am I?

**Comment by daniel-beck** [comment]
Also added the ability to override the issue tracker URL if needed. Some plugin have weird plugin IDs that aren't reflected in component names.

**Review by timja — APPROVED** [review]

**Comment by halkeye** [comment]
> Why are we claiming a default branch of `master` when we don't even publish the SCM?

I think i was trying to avoid breaking things by keeping old behavior, but your absolutely right, its a new field, and plugin site shouldn't be trying to get readme if there's no repo data anyways.

**Comment by daniel-beck** [comment]
> I have it prepared locally but not yet pushed

Thanks 😕

**Review by daniel-beck — APPROVED** [review]
I think this is good to go now 👍

**Review by olblak — APPROVED** [review]

**Review by yJunS — APPROVED** [review]

**Review by SonyViao — APPROVED** [review]

**Comment by daniel-beck** [comment]
After some more discussions, we've decided to store the metadata in plugin metadata ( https://github.com/jenkins-infra/repository-permissions-updater ) and only consume the generated `issues.index.json` here, transforming output a bit. So we won't need the overrides and such.

https://github.com/jenkins-infra/repository-permissions-updater/pull/1806 implemented this and has further references.

**Comment by daniel-beck** [comment]
#492 implements the issue tracker metadata information now as pass-through from https://github.com/jenkins-infra/repository-permissions-updater.

@halkeye I'll add default branches to the JSON in a separate PR if you still want/need that for the plugin site (to render docs from a non-`master` default branch IIRC), just let me know.

**Comment by halkeye** [comment]
yes please!

**Comment by daniel-beck** [comment]
#495 takes care that. Meanwhile I'm closing this.

**Pull request closed without merging**
