### PR TITLE
Remove duplication between deprecations and ignores

### PR DESCRIPTION
**Pull request by zbynek**
@daniel-beck this should make it easier to inform users about suspended plugins (no duplication between ignores and deprecations). General thoughts 👍 / 👎 ? If it's OK I'll double-check that no information got lost here.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Oh that's a nice approach. I'll give it a closer look when I have some time, but from a quick look it looks very promising!

Also TODO (perhaps not now but before merge): Update README and resource file header comments.

**Comment by daniel-beck** [comment]
Sorry for the delay here, my spare time is fairly limited right now.

**Review by daniel-beck — APPROVED** [review]
This is great, thank you very much!

That data migration 🤩

Will merge and release once you confirm you're OK with my changes.

**Comment by zbynek** [comment]
@daniel-beck thanks for reviewing, your changes look good!

**Pull request merged**
