### PR TITLE
adopt-this-plugin: flaky-test-handler

### PR DESCRIPTION
**Pull request by scpeters**
I don't have the knowledge or bandwidth to maintain this plugin

### CODE REVIEW

**Comment by daniel-beck** [comment]
Thanks for letting us know! I've applied the label to the GitHub repo, that should have the same result of letting people know via the plugin site and in Jenkins directly.

**Comment by scpeters** [comment]
thanks

**Comment by daniel-beck** [comment]
Update: It works: https://plugins.jenkins.io/flaky-test-handler/

**Comment by vtintillier** [comment]
Hello @daniel-beck 

I sent a message before this plugin was formally put for adaption on jenkins-dev [1].
Is it the right process to just send a message there, or should I create some kind of `jenkins-infra` issue/PR?

Thanks

[1] https://groups.google.com/g/jenkinsci-dev/c/rrz04NdiQZw

**Comment by daniel-beck** [comment]
@vtintillier Ultimately this needs to be reflected in https://github.com/jenkins-infra/repository-permissions-updater but how you get there is fairly free-form. The usual process is documented in https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

I recommend syncing with the other prospective maintainer (and perhaps @scpeters) first so you agree on what the future looks like.

**Pull request closed without merging**
