### PR TITLE
Added "devsecops" category

### PR DESCRIPTION
**Pull request by GavinF17**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Could you please provide a list of plugins which would benefit from this label?

**Comment by GavinF17** [comment]
My own, https://github.com/jenkinsci/uleska-plugin

As well as contrast-continuous-application-security, snyk-security-scanner, fortify, sonar and others

**Comment by daniel-beck** [comment]
Should have a corresponding core change.

**Comment by GavinF17** [comment]
> Should have a corresponding core change.

See https://github.com/jenkinsci/jenkins/pull/4927

**Comment by oleg-nenashev** [comment]
Based on the feedback, I have added the category to the suggested plugins. Will go ahead and merge this PR

**Comment by daniel-beck** [comment]
@oleg-nenashev Please hold off such merges until the core PR is actually merged and released.

**Pull request merged**
