### PR TITLE
[INFRA-2292] Read Url from the plugin manifest before looking for pom.xml#/project/url

### PR DESCRIPTION
**Pull request by jglick**
[INFRA-2292](https://issues.jenkins-ci.org/browse/INFRA-2292)

**Untested**. Do we need to just run CI on it and manually verify?

@oleg-nenashev

### CODE REVIEW

**Comment by PierreBtz** [comment]
@oleg-nenashev do you think we could get this moving somehow? I bet with the latest blogpost, other people will try to use the `artifactid` variable in their pom and end up in this situation.
Happy to help if I can do something on my end.

**Comment by zbynek** [comment]
@daniel-beck thanks for your patience with my questions in the ticket.

https://ci.jenkins.io/job/Infra/job/update-center2/job/PR-303/5/artifact/output/latest/plugin-documentation-urls.json looks goot, can this be merged?

(meanwhile the number of plugins affected grew from 2 to 4)

**Comment by daniel-beck** [comment]
This fixed 4 plugins that had placeholders before:

* https://github.com/jenkinsci/aws-beanstalk-releaser-plugin
* https://github.com/jenkinsci/envinject-api-plugin
* https://github.com/jenkinsci/jenkins-ignore-committer-strategy-plugin
* https://github.com/jenkinsci/pipeline-cps-http-plugin

It regressed the following plugins/URLs:

* https://wiki.jenkins-ci.org/display/JENKINS/discoBit+Autoconfig+Plugin was replaced by http://discobit.com
* From no docs URL to https://hudson.dev.java.net/plugin/SSSCM
* From no docs URL to http://jenkins-ci.org/plugin/build-requester/
* From no docs URL to http://jenkins-ci.org/plugin/collabnet-automic-deploy/
* From no docs URL to http://jenkins-ci.org/plugin/collabnet-uc4-deploy/
* From no docs URL to http://jenkins-ci.org/plugin/deploygate-plugin/
* From no docs URL to http://jenkins-ci.org/plugin/drecycler/
* From no docs URL to http://jenkins-ci.org/plugin/keep-slave-disconnected/
* From no docs URL to http://jenkins-ci.org/plugin/monitor-remote-job/
* From no docs URL to http://jenkins-ci.org/plugin/oki-docki/
* From no docs URL to http://jenkins-ci.org/plugin/trial-balloon/
* From no docs URL to http://jenkins-ci.org/plugin/writable-filesystem-monitor/
* From no docs URL to https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/declarative-pipeline-migration-assistant
* From no docs URL to https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/declarative-pipeline-migration-assistant-api

So I wouldn't quite consider this a success…

**Comment by jglick** [comment]
I am trying to understand why

```bash
curl -sL 'https://updates.jenkins-ci.org/update-center.actual.json?version=2.190.3' | jq -r '.plugins | .["artifact-manager-s3"].wiki'
```

is producing `https://plugins.jenkins.io/artifact-manager-s3` whereas

```bash
unzip -p ~/.m2/repository/io/jenkins/plugins/artifact-manager-s3/1.7/artifact-manager-s3-1.7.hpi META-INF/MANIFEST.MF | egrep '^Url:'
```

is `https://github.com/jenkinsci/artifact-manager-s3-plugin` as expected.

**Comment by jglick** [comment]
Hmm,

```bash
curl -sL https://ci.jenkins.io/job/Infra/job/update-center2/job/master/163/consoleText | fgrep artifact-manager-s3
```

claims that the plugin was downloaded, but says nothing else about it. Something broken here?

**Comment by daniel-beck** [comment]
@jglick  We always link to the plugin site from the UC metadata, as that a generally more useful entry point than the actual "wiki" page, displaying various metadata. This change affects only https://updates.jenkins-ci.org/current/plugin-documentation-urls.json which is used by the plugin site. See also https://github.com/jenkinsci/jenkins/pull/4273 for even more references to the UC URLs over plugin built-in URLs.

**Pull request merged**
